[build]
  publish = "public/"
  command = "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[build.environment]
  PHP_VERSION = "8.2"

# Redirections pour les routes Laravel
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200